services:
  api:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
    command: node dist/app.js
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    volumes:
      - db-data:/data/db
    environment:
      - DB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    restart: always
volumes:
  db-data:
